# .coderabbit.yaml
language: "ru" # Чтобы робот писал на русском языке

reviews:
  # Разрешаем проверку для абсолютно всех целевых веток (убираем ограничение дефолтной ветки)
  target_branches:
    - "*"