# .coderabbit.yaml
language: "ru" # Робот будет писать на русском языке

reviews:
  auto_review:
    enabled: true
    # Разрешаем проверку для абсолютно всех веток (убираем ограничение)
    base_branches:
      - ".*"
